<style>
    .error{
        color: red;
    }
</style>
<!-- Horizontal form modal -->
<div id="modal_form_horizontal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h5 class="modal-title"><?php echo $header_title; ?></h5>
            </div>

            <form enctype="multipart/form-data" method="post" onsubmit="return false;" class="form-horizontal ">
                <div class="modal-body">
                    <input type="hidden" name="ba_id"  class="form-control">
                    <div class="form-group">
                        <label class="control-label col-sm-3">Category Banner</label>
                        <div class="col-sm-9">
                            <select  name="bc_id" class="select-search">
                                <option value="-1">Chose</option>
                                <?php foreach ($category_data as $val) { ?>
                                    <option value="<?php echo $val->bc_id ?>"><?php echo $val->bc_name ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Name</label>
                        <div class="col-sm-9">
                            <input type="text"  name="ba_name"  class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Decription</label>
                        <div class="col-sm-9">
                            <textarea style="width: 500px; height: 110px;" rows="5" cols="5" class="form-control" name="ba_description" ></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Image</label>
                        <div class="col-sm-9">
                            <button style="width: 70px; display: inline-block; vertical-align: top;" onclick="BrowseServer('ba_image_link_img', 'ba_image_link');" class="btn btn-block btn-primary " >Upload</button>
                            <input  name="ba_image_link_img" type="image" style="max-width: 200px;"  src="" alt="">
                            <input type="hidden" name="ba_image_link"   class="form-control ">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Link</label>
                        <div class="col-sm-9">
                            <input type="text"   name="ba_link"  class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Sort</label>
                        <div class="col-sm-9">
                            <input value="1" type="text" number="true" name="ba_sort"  class="form-control">
                        </div>
                    </div>

                </div>


                <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                    <button  type="submit" class="btn btn-primary btn-submit-content">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<p id="demo"></p>
<!-- /horizontal form modal -->
<script type="text/javascript">
    var columns = {'ba_id': 'inputtext','bc_id': 'select','ba_name': 'inputtext', 'ba_description': 'textarea','ba_image_link': 'image','ba_sort': 'inputtext','ba_link': 'inputtext'};
</script>
