<style>
    .error{
        color: red;
    }
</style>
<!-- Horizontal form modal -->
<div id="modal_form_horizontal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h5 class="modal-title"><?php echo $header_title; ?></h5>
            </div>

            <form enctype="multipart/form-data" method="post" onsubmit="return false;" class="form-horizontal ">
                <div class="modal-body">
                    <input type="hidden" name="ne_id"  class="form-control">
                    
                    <div class="form-group">
                        <label class="control-label col-sm-3">Subject</label>
                        <div class="col-sm-9">
                            <input type="text" required="true" name="ne_subject"  class="form-control">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="control-label col-sm-3">Content</label>
                        <div class="col-sm-9">
                            <textarea style="width: 500px; height: 110px;" rows="5" cols="5" class="form-control " id="description_ckeditor" name="ne_content" ></textarea>
                        </div>
                    </div>
                </div>


                <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                    <button  type="submit" class="btn btn-primary btn-submit-content">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<p id="demo"></p>
<!-- /horizontal form modal -->
<script type="text/javascript">
    var columns = {'ne_id': 'inputtext','ne_subject': 'inputtext', 'ne_content': 'ckeditor'};
   
</script>
