<style>
    .error {
        color: red;
    }
</style>
<!-- Horizontal form modal -->
<div id="modal_form_horizontal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h5 class="modal-title"><?php echo $header_title; ?></h5>
            </div>

            <form enctype="multipart/form-data" method="post" onsubmit="return false;" class="form-horizontal ">
                <div class="modal-body">
                    <input type="hidden" name="hlv_id" class="form-control">
                    <div class="form-group">
                        <label class="control-label col-sm-3">Image</label>
                        <div class="col-sm-9">
                            <button style="width: 70px; display: inline-block; vertical-align: top;"
                                    onclick="BrowseServer('hlv_image_link_img', 'hlv_image_link');"
                                    class="btn btn-block btn-primary ">Upload
                            </button>
                            <input name="hlv_image_link_img" type="image" style="max-width: 200px;" src="" alt="">
                            <input type="hidden" name="hlv_image_link" class="form-control ">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Name</label>
                        <div class="col-sm-9">
                            <input type="text" name="hlv_name" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Position Title</label>
                        <div class="col-sm-9">
                            <input type="text" name="hlv_position" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Age</label>
                        <div class="col-sm-9">
                            <input type="text" name="hlv_age" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Gender</label>
                        <div class="col-sm-9">
                            <select name="hlv_gender" class="select-search">
                                <option value="1">Male</option>
                                <option value="2">Female</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Experience</label>
                        <div class="col-sm-9">
                            <input type="text" name="hlv_experience" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Decription</label>
                        <div class="col-sm-9">
                            <textarea style="width: 500px; height: 110px;" rows="5" cols="5" class="form-control"
                                      name="hlv_description"></textarea>
                        </div>
                    </div>


                </div>


                <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary btn-submit-content">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<p id="demo"></p>
<!-- /horizontal form modal -->
<script type="text/javascript">
    var columns = {
        'hlv_id': 'inputtext',
        'hlv_name': 'inputtext',
        'hlv_position': 'inputtext',
        'hlv_age': 'inputtext',
        'hlv_experience': 'inputtext',
        'hlv_description': 'textarea',
        'hlv_image_link': 'image',
        'hlv_gender': 'select',
    };
</script>
