<style>
    .error{
        color: red;
    }
</style>
<!-- Horizontal form modal -->
<div id="modal_form_horizontal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h5 class="modal-title"><?php echo $header_title; ?></h5>
            </div>

            <form enctype="multipart/form-data" method="post" onsubmit="return false;" class="form-horizontal ">
                <div class="modal-body">
                    <input type="hidden" name="plo_id"  class="form-control">
                    <div class="form-group">
                        <label class="control-label col-sm-3">Category </label>
                        <div class="col-sm-9">
                            <select  name="po_id" class="select-search">
                                <option value="-1">Chose</option>
                                <?php foreach ($category_data as $val) { ?>
                                    <option value="<?php echo $val->po_id ?>"><?php echo $val->po_name ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Name</label>
                        <div class="col-sm-9">

                            <input type="text"  required="true" name="plo_name"  class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Detail</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control colorpicker-input-initial"  >
                            <input class="show-color" type="hidden" name="plo_detail">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Decription</label>
                        <div class="col-sm-9">
                            <textarea style="width: 500px; height: 110px;" rows="5" cols="5" class="form-control" name="plo_description" ></textarea>
                        </div>
                    </div>

                </div>


                <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                    <button  type="submit" class="btn btn-primary btn-submit-content">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<p id="demo"></p>
<!-- /horizontal form modal -->
<script type="text/javascript">
    var columns = {'plo_id': 'inputtext', 'po_id': 'select', 'plo_name': 'inputtext', 'plo_detail': 'color', 'plo_description': 'textarea'};
    $(document).ready(function () {
        $(".colorpicker-input-initial").spectrum({
            allowEmpty:true,
            preferredFormat: "hex3",
            showInitial: true,
            showInput: true,
            hide: function (c) {
                $(".show-color").val(c.toHexString());
            }
        });
    });
</script>

