<?php echo $this->partial('partial/menu_top_desktop') ?>
    <!-- Header -->
    <header id="myCarousel" class="carousel slide">
        <div id="slider1" class="rev_slider" data-version="5.0">
            <ul>
                <?php if ($sliders) {
                    foreach ($sliders as $slider) { ?>
                        <li data-transition="random">
                            <img src="<?php echo $slider->ba_image_link ?>">

                            <div class="carousel-caption">
                                <h1><?php echo $slider->ba_name ?></h1>
                                <p><?php echo $slider->ba_description ?></p>
                            </div>
                        </li>
                    <?php }
                } ?>
            </ul>
        </div>
    </header>

    <!-- Services Section -->
    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Các huấn luyện viên </h2>
                </div>
            </div>
            <div class="row text-center">
                <?php if ($coachs) {
                    foreach ($coachs as $coach) { ?>
                        <div class="col-md-4 col-sm-4 ">
                            <div class="info-hlv">
                                <div class="hlv-content">
                                    <div
                                        style="background: url('<?php echo $coach->hlv_image_link ?>') no-repeat top center;"
                                        class="img-hlv hlv1"></div>
                                    <h4 class="service-heading"><?php echo $coach->hlv_name ?></h4>
                                    <h5 style="color:#a7a9ac;text-transform: none;font-size: 15px" ><?php echo $coach->hlv_position ?></h5>
                                    <div class="hover-hlv-area">

                                        <a data-dismiss="modal" data-toggle="modal"
                                           data-target="#popupInfoHlv-<?php echo $coach->hlv_id ?>"
                                           href="javascript:;"
                                           class="animated fadeInUp btn-hlv-area btn-hlvinfo">Tìm hiểu</a>
                                        <a data-rel="<?php echo $coach->hlv_id ?>" data-dismiss="modal"
                                           data-toggle="modal" <?php if (!$user) { ?> data-target="#popupLogin" <?php } ?>
                                           href="javascript:;"
                                           class="animated fadeInUp btn-hlv-area btn-hlvplay <?php if ($user) { ?> btn-playgame  <?php } ?>">Tham
                                            gia
                                            ngay</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php }
                } ?>
            </div>
        </div>
    </section>

    <!-- Portfolio Grid Section -->
    <section id="portfolio" class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">thể lệ cuộc thi</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?php if ($infographic) { ?>
                        <img style="margin: 0 auto;max-height: 345px" class="img-responsive"
                             src="<?php echo $infographic->ba_image_link ?>" alt="<?php echo $infographic->ba_name ?>">
                    <?php } ?>
                </div>
            </div>
            <div style="margin: 60px auto;" class="row ">
                <div class="text-thele-area">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                    industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
                    and scrambled it to make a type specimen book. It has survived not only five centuries, but also the
                    leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s
                    with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop
                    publishing software like Aldus PageMaker including versions of Lorem Ipsum.

                    Where does it come from?

                    Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of
                    classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin
                    professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words,
                    consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical
                    literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33
                    of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This
                    book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of
                    Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
                    The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.
                    Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in
                    their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                    industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
                    and scrambled it to make a type specimen book. It has survived not only five centuries, but also the
                    leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s
                    with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop
                    publishing software like Aldus PageMaker including versions of Lorem Ipsum.

                    Where does it come from?

                    Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of
                    classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin
                    professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words,
                    consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical
                    literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33
                    of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This
                    book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of
                    Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
                    The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.
                    Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in
                    their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
                </div>
            </div>
        </div>
    </section>

    <!-- About Section -->
    <section id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading text-head-gallery">Thư viện bài thi</h2>
                </div>
            </div>
            <div class="row search-gallery-area">
                <form id="filter-kol" onsubmit="return false;">
                    <div class="col-md-4 col-sm-4">
                        <input id="datepicker" class="filter-name" type="text" name="created_at"
                               placeholder="Ngày Đăng"/>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="select2-wrapper">
                            <select name="hlv_id"
                                    class=" select-custom form-control select-2">
                                <?php if ($coachs) {
                                    foreach ($coachs as $coach) { ?>
                                        <option
                                            value="<?php echo $coach->hlv_id ?>"><?php echo $coach->hlv_name ?></option>
                                    <?php }
                                } ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="form-button-wrapper">
                            <button type="button" class="btn btn-search-kol">Tìm Kiếm</button>
                        </div>
                    </div>
                </form>
            </div>
            <div id="gallery-posts" class="row ">
                <?php if (count($posts) > 0) {
                    foreach ($posts as $po) { ?>
                        <div class="col-md-4 col-sm-4">
                            <div class="user-posts">
                                <h3 class="username-post">
                                    <?php echo $po->UserModel->us_name ?>
                                </h3>
                                <p>Bài Thi : <em><?php echo $po->p_description ?></em></p>
                                <p>Giáo Viên : <em><?php echo $po->ManagerHlvModel->hlv_name ?></em></p>
                            </div>
                        </div>
                    <?php }
                } ?>
            </div>
            <div class="row text-center">
                <nav id="kol-pagination" class="hq-kol-pagination" aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="javascript:;" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li><a href="javascript:;">1</a></li>
                        <li><a href="javascript:;">2</a></li>
                        <li><a href="javascript:;">3</a></li>
                        <li><a href="javascript:;">4</a></li>
                        <li><a href="javascript:;">5</a></li>
                        <li>
                            <a href="javascript:;" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </section>

    <!-- Team Section -->
    <section id="team" class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading text-head-gallery">tin tức & sự kiện</h2>
                </div>
            </div>
            <div class="row">
                <?php if ($blogs) {
                    foreach ($blogs as $news) { ?>
                        <div class="col-md-4 col-sm-4">
                            <div class="hq-blog">
                                <div class="hq-img-blog">
                                    <img src="<?php echo $news->n_image_link ?>"
                                         alt="<?php echo $news->n_name ?>">
                                </div>
                                <div class="hq-content-blog">
                                    <a target="_blank"
                                       href="<?php echo $this->url->get("blogs/detail/") . $news->n_seo_link ?>">
                                        <h3><?php echo $news->n_name ?></h3></a>
                                    <div class="hq-meta-blog">
                                        <?php echo $news->showCreateDate() ?>
                                    </div>
                                    <div class="short-description">
                                        <?php echo nl2br($news->n_short_description) ?>
                                    </div>
                                    <a target="_blank" class="hq-readmore"
                                       href="<?php echo $this->url->get("blogs/detail/") . $news->n_seo_link ?>">Xem
                                        Thêm <i
                                            class="fa fa-angle-double-right"></i></a>
                                </div>
                            </div>
                        </div>
                    <?php }
                } ?>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <a href="<?php echo $this->url->get("blogs") ?>" class="btn-loadmore">Xem Thêm</a>
                </div>
            </div>
        </div>
    </section>


<?php echo $this->partial('partial/footer') ?>