<style>
    .error{
        color: red;
    }
</style>
<!-- Horizontal form modal -->
<div id="modal_form_horizontal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h5 class="modal-title"><?php echo $header_title; ?></h5>
            </div>

            <form enctype="multipart/form-data" method="post" onsubmit="return false;" class="form-horizontal ">
                <div class="modal-body">
                    <input type="hidden" name="mn_id"  class="form-control">
                    <div class="form-group">
                        <label class="control-label col-sm-3">Category Menu</label>
                        <div class="col-sm-9">
                            <select  name="mn_parent_id" class="select-search">
                                <option value="0">Chose</option>
                                <?php foreach ($category_data as $val) { ?>
                                <option  value="<?php echo $val['id'] ?>"><?php echo $val['name_parent'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Title</label>
                        <div class="col-sm-9">
                            <input type="text" required="true" name="mn_name"  class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Link</label>
                        <div class="col-sm-9">
                            <input type="text" required="true"  name="mn_link"  class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Sort</label>
                        <div class="col-sm-9">
                            <input value="1" type="text" number="true" name="mn_sort"  class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Status</label>
                        <div class="col-sm-9">
                            <div class="checkbox checkbox-switch">
                                <label>
                                    <input name="mn_status" value="0" type="checkbox" data-on-color="success" data-off-color="warning" data-on-text="Show" data-off-text="Hide" class="switch" checked="true">
                                    Show/hide
                                </label>
                            </div>
                        </div>
                    </div>

                </div>


                <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                    <button  type="submit" class="btn btn-primary btn-submit-content">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<p id="demo"></p>
<!-- /horizontal form modal -->
<script type="text/javascript">
    var columns = {'mn_id': 'inputtext', 'mn_parent_id': 'select', 'mn_name': 'inputtext', 'mn_sort': 'inputtext', 'mn_link': 'inputtext', 'mn_status': 'checkbox-switch'};
</script>
