<h1 class="error-title">500</h1>
<h6 class="text-semibold content-group"><?php echo $this->language->_e("Oops, an error has occurred. Internal server error!"); ?></h6>

<div class="row">
    <div class="col-lg-4 col-lg-offset-4 col-sm-6 col-sm-offset-3">
        <form action="#" class="main-search">
            <div class="row">
                <div class="col-sm-12">
                    <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-primary btn-block content-group"><i class="icon-circle-left2 position-left"></i> <?php echo $this->language->_e("Back to home"); ?></a>
                </div>
            </div>
        </form>
    </div>
</div>
