<!-- FB -->
<script>
    window.fbAsyncInit = function () {
        FB.init({
            appId: '<?php echo $this->module_config_frontend->FACEBOOK_ID; ?>',
            xfbml: true,
            version: 'v2.2'
        });
    };

    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {
            return;
        }
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<!-- FB -->
<!-- Google -->
<script src="https://apis.google.com/js/client.js"></script>
<!-- Google -->