<?php echo $this->partial('partial/menu_top_desktop') ?>

<section id="hq-breadcrumb">
    <div class="container">
        <div class="row">
            <div class="over-lay-area1"></div>
            <div class="col-lg-12 text-center">
                <h2 class="section-heading text-head-gallery">tin tức & sự kiện</h2>
            </div>
        </div>
    </div>
</section>

<!-- Team Section -->
<section id="team" class="bg-light-gray">
    <div class="container">
        <div class="row blogs-list-area">
            <?php if ($data) {
                foreach ($data as $news) { ?>
                    <div class="col-md-4 col-sm-4">
                        <div class="hq-blog">
                            <div class="hq-img-blog">
                                <a target="_blank" href="<?php echo $this->url->get("blogs/detail/").$news->n_seo_link ?>"><img src="<?php echo $news->n_image_link ?>"
                                                                                                                                alt="<?php echo  $news->n_name  ?>"></a>
                            </div>
                            <div class="hq-content-blog">
                                <a target="_blank" href="<?php echo $this->url->get("blogs/detail/").$news->n_seo_link ?>"><h3><?php echo  $news->n_name  ?></h3></a>
                                <div class="hq-meta-blog">
                                    <?php echo  $news->showCreateDate()  ?>
                                </div>
                                <div class="short-description">
                                    <?php echo nl2br($news->n_short_description)    ?>
                                </div>
                                <a target="_blank" class="hq-readmore" href="<?php echo $this->url->get("blogs/detail/").$news->n_seo_link ?>">Xem Thêm <i
                                        class="fa fa-angle-double-right"></i></a>
                            </div>
                        </div>
                    </div>
                <?php }
            } ?>
        </div>
        <div class="row">
            <div class="col-md-12">
                <a href="javascript:;" class="btn-loadmore btn-loadmore-blogs">Xem Thêm</a>
            </div>
        </div>
    </div>
</section>


<?php echo $this->partial('partial/footer') ?>