<table class="table table-bordered table-hover datatable-highlight">
    <thead>
    <tr class="success">
        <th>User ID</th>
        <th>Full Name</th>
        <th>User Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Create Date</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody class="tbody-search">
    <?php if ($data) { ?>
        <?php foreach ($data as $key => $val) { ?>
            <tr>
                <td><?php echo $val->us_id ?></td>
                <td><?php echo $val->us_full_name ?></td>
                <td><?php echo $val->us_name ?></td>
                <td><?php echo $val->us_email ?></td>
                <td><?php echo $val->us_phone ?></td>
                <td><?php echo $val->setCreateDate(); ?></td>
                <td>
                    <?php if ($val->us_status == 1) { ?>
                        <span class="label label-success">Show</span>
                    <?php } else { ?>
                        <span class="label label-warning">Hide</span>
                    <?php } ?>
                </td>
                <td>
                    <button onclick="showPopup(<?php echo $val->us_id ?>)" data-original-title="Edit"
                            data-toggle="modal" data-target="#modal_form_horizontal" data-popup="tooltip" type="button"
                            class="btn btn-info btn-icon btn-edit-content">
                        <i class="icon-pencil7"></i>
                    </button>

                    <button data-rel="<?php echo $val->us_id ?>" data-original-title="Remove" data-popup="tooltip"
                            type="button" class="btn btn-danger btn-icon btn-delete-content">
                        <i class="icon-trash"></i>
                    </button>
                </td>
            </tr>
            <?php
        }
    }
    ?>

    </tbody>
</table>
