<div class="footer-mobile-area">
    <div class="social">
        <p class="ng-binding">Our social places</p>
        <ul>
            <li class="ng-scope" >
                <a  class="icon-button" target="_blank">
                    <span class="icon ico-facebook black" >&nbsp;</span>
                </a>
            </li>
            <li class="ng-scope" >
                <a  class="icon-button" target="_blank">
                    <span class="icon ico-twitter black" >&nbsp;</span>
                </a>
            </li>
            <li class="ng-scope" >
                <a  class="icon-button" target="_blank">
                    <span class="icon ico-instagram black" >&nbsp;</span>
                </a>
            </li>
            <li class="ng-scope" >
                <a  class="icon-button" target="_blank">
                    <span class="icon ico-pinterest black" >&nbsp;</span>
                </a>
            </li>
            <li class="ng-scope" >
                <a  class="icon-button" target="_blank">
                    <span class="icon ico-spotify black" >&nbsp;</span>
                </a>
            </li>
        </ul>
    </div>
</div>