<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <span class="copyright">Copyright © 2016 by <span class="text-hq">HQ Solution</span>.</span>
            </div>
            <div class="col-md-4">
                <ul class="list-inline social-buttons">
                    <li><a href="#">
                            <img src="<?php echo $this->url->get("public/FrontendCore/") ?>images/icon-fb.png" alt="">
                        </a>
                    </li>
                    <li><a href="#">
                            <img src="<?php echo $this->url->get("public/FrontendCore/") ?>images/icon-gg.png" alt="">
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-inline quicklinks">
                    <li>
                        <a href="#">Chính Sách</a>
                    </li>
                    <li>
                        <a href="#">Thông Tin</a>
                    </li>
                    <li>
                        <a href="#">Liên Hệ</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>