<div data-widget-cid="widget-2"></div>
<div data-widget-cid="widget-3"></div>
<div data-widget-cid="widget-4" id="shopping-history" class="">
<!--    <div class="container shopping-history-relative">-->
<!--        <span data-role="show" class="show-history">Recently Viewed</span>-->
<!--    </div>-->
    <div class="shopping-history-content">
        <div data-role="list-box" class="container shopping-history-list"></div>
    </div>
</div>
<div style="z-index: 99; display: none; position: absolute; left: -9999px; top: -9999px;" data-widget-cid="widget-9"
     data-role="popup" class="ui-fixed-panel-tip-popup ui-fixed-panel-qr-code-popup">
    <img class="ui-fixed-panel-qr-code-image" src="img/T1HLX.png" alt="">
    <div class="ui-fixed-panel-qr-code-tip">Enjoy convenient order tracking.</div>
</div>
<div style="z-index: 99; position: absolute; left: -190px; top: 0px; display: none;" data-widget-cid="widget-11"
     data-role="popup" class="ui-fixed-panel-tip-popup">
    Tell us how you would improve AliExpress!
</div>
<div data-widget-cid="widget-6" style="position: fixed; visibility: visible; right: 5%; bottom: 12%;"
     class="ui-fixed-panel">
    <div style="visibility: visible;" class="ui-fixed-panel-shares" data-role="sharesArea">
        <div data-widget-cid="widget-7" class="ui-fixed-panel-unit ui-fixed-panel-share ui-fixed-panel-facebook">
            <a href="https://www.facebook.com/AliExpress" data-role="trigger"></a>
        </div>
    </div>



    <div class="ui-fixed-panel-operation" data-role="operationArea">
       
        <div style="visibility: hidden; opacity: 1;" data-widget-cid="widget-13"
             class="ui-fixed-panel-unit ui-fixed-panel-go-top" data-role="hide">
            <a class="btn-scroll-to-top" href="javascript:;" data-role="trigger"></a>
        </div>
    </div>
</div>
<div data-widget-cid="widget-15"></div>
<div data-widget-cid="widget-16"></div>

<div data-widget-cid="widget-4"></div>
<div id="goog-gt-tt" class="skiptranslate" dir="ltr">
    <div style="padding: 8px;">
        <div>
            <div class="logo"><img src="img/translate_24dp.png" height="20" width="20"></div>
        </div>
    </div>
    <div class="top" style="padding: 8px; float: left; width: 100%;"><h1 class="title gray">Original text</h1></div>
    <div class="middle" style="padding: 8px;">
        <div class="original-text"></div>
    </div>
    <div class="bottom" style="padding: 8px;">
        <div class="activity-links"><span class="activity-link">Contribute a better translation</span><span
                class="activity-link"></span></div>
        <div class="started-activity-container">
            <hr style="color: #CCC; background-color: #CCC; height: 1px; border: none;">
            <div class="activity-root"></div>
        </div>
    </div>
    <div style="display: none;" class="status-message"></div>
</div>