<style>
    .error {
        color: red;
    }
</style>
<!-- Horizontal form modal -->
<div id="modal_form_horizontal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h5 class="modal-title"><?php echo $header_title; ?></h5>
            </div>

            <form enctype="multipart/form-data" method="post" onsubmit="return false;" class="form-horizontal ">
                <div class="modal-body">
                    <input type="hidden" name="co_id" class="form-control">
                    <div class="form-group">
                        <label class="control-label col-sm-3">Name</label>
                        <div class="col-sm-9">
                            <input type="text"  name="co_name" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Code</label>
                        <div class="col-sm-9">
                            <input type="text"  name="co_code" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Date Start</label>
                        <div class="col-sm-9">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="icon-calendar22"></i></span>
                                <input name="co_date_start" class="form-control daterange-single" value="php"
                                       type="text">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Date End
                        </label>
                        <div class="col-sm-9">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="icon-calendar22"></i></span>
                                <input name="co_date_end" class="form-control daterange-single" value="null"
                                       type="text">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Type</label>
                        <div class="col-sm-9">
                            <select name="co_type" class="select-search">
                                <option value="1">Percentage</option>
                                <option value="2">Fixed Amount</option>

                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Discount</label>
                        <div class="col-sm-9">
                            <input  type="text"  name="co_discount" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Total Amount</label>
                        <div class="col-sm-9">
                            <input type="text" name="co_total" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Number Coupon</label>
                        <div class="col-sm-9">
                            <input  type="text" value="1"  name="co_number" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">User Number </label>
                        <div class="col-sm-9">
                            <input  type="text" value="1"  name="co_uses_total" class="form-control">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-sm-3">Status</label>
                        <div class="col-sm-9">
                            <div class="checkbox checkbox-switch">
                                <label>
                                    <input name="co_status" value="0" type="checkbox" data-on-color="success"
                                           data-off-color="warning" data-on-text="Show" data-off-text="Hide"
                                           class="switch" checked="true">
                                    Show/hide
                                </label>
                            </div>
                        </div>
                    </div>

                </div>


                <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary btn-submit-content">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<p id="demo"></p>
<!-- /horizontal form modal -->
<script type="text/javascript">
    var columns = {
        'co_id': 'inputtext',
        'co_name': 'inputtext',
        'co_code': 'inputtext',
        'co_type': 'select',
        'co_total':'inputtext',
        'co_number':'inputtext',
        'co_date_start':'inputtext',
        'co_date_end':'inputtext',
        'co_uses_total':'inputtext',
        'co_discount': 'inputtext',
        'co_status': 'checkbox-switch'
    };
</script>
