<div class="wrapper">
    <div class="blog-list-area">
        <?php echo $this->partial('news/_menu_news') ?>

        <div class="main-blog-list">
            <img class="image-head" src="<?php echo isset($news) ? $news->n_image_link : '' ?>" alt="">
            <h1><?php echo isset($news) ? $news->n_name : '' ?></h1>
            <div class="time-coment-share">
                <ul>
                    <li>
                        <i class="fa fa-clock-o " aria-hidden="true"></i>
                        <?php echo isset($news) ? $news->showCreateDate() : '' ?>
                    </li>
                    <li>
                        <div id="fb-root"></div>
                        <script>(function (d, s, id) {
                                var js, fjs = d.getElementsByTagName(s)[0];
                                if (d.getElementById(id)) return;
                                js = d.createElement(s);
                                js.id = id;
                                js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.6&appId=1388971278034665";
                                fjs.parentNode.insertBefore(js, fjs);
                            }(document, 'script', 'facebook-jssdk'));</script>
                        <div class="fb-like"
                             data-href="<?php echo $this->url->get("news/detail/") . $news->n_seo_link ?>"
                             data-layout="button_count" data-action="like" data-show-faces="true"
                             data-share="true"></div>
                    </li>
                </ul>
            </div>
            <div class="content-news-detail">
                <h2 class="init_content oh"><?php echo isset($news) ? $news->n_name : '' ?></h2>
                <div class="clearfix">
                </div>
                <div id="ContentDetail">
                    <?php echo isset($news) ? $news->n_description : '' ?>
                </div>
            </div>
            <div class="tag-area">
                <span>TAGS : </span>
                <?php echo isset($news) ? $news->showKeywords() : '' ?>
            </div>
            <div class="social">
                <ul>
                    <li class="ng-scope">
                        <span class="ng-binding">CHIA SẺ</span>
                    </li>
                    <li class="ng-scope">
                        <div style="margin: 0;" class="addThisButtons rowfluid clearfix socialProduct__container">
                            <!-- Go to www.addthis.com/dashboard to customize your tools -->
                            <script type="text/javascript"
                                    src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-571ca9f3d29cb3c0"></script>
                            <!-- Go to www.addthis.com/dashboard to customize your tools -->
                            <div class="addthis_sharing_toolbox"></div>
                        </div>
                    </li>

                </ul>
            </div>
            <div id="fb-root"></div>
            <div id="fb-root"></div>
            <script>(function (d, s, id) {
                    var js, fjs = d.getElementsByTagName(s)[0];
                    if (d.getElementById(id)) return;
                    js = d.createElement(s);
                    js.id = id;
                    js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.6&appId=<?php echo $this->module_config_frontend->FACEBOOK_ID;?>";
                    fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));</script>
            <div class="fb-comments" data-href="<?php echo $this->config['rootUrl'] . $news->showSeoLink(); ?>"
                 data-width="100%" data-numposts="5"></div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>