<style>
    .error{
        color: red;
    }
</style>
<!-- Horizontal form modal -->
<div id="modal_form_horizontal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h5 class="modal-title"><?php echo $header_title; ?></h5>
            </div>

            <form enctype="multipart/form-data" method="post" onsubmit="return false;" class="form-horizontal ">
                <div class="modal-body">
                    <input type="hidden" name="col_id"  class="form-control">
                    <div class="form-group">
                        <label class="control-label col-sm-3">Category Parent</label>
                        <div class="col-sm-9 select-category-product-area ">
                            <select id="select-category-product" name="col_parent_id" class="select-search">
                                <option value="0">Chose</option>
                                <?php
                                foreach ($category_data as $val) {
                                    ?>
                                    <option  value="<?php echo $val->id ?>"><?php echo $val->name_parent ?></option>
                                <?php }
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Title</label>
                        <div class="col-sm-9">
                            <input type="text" required="true" name="col_name"  class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Seo Link <br>(* System auto create Seo Link )</label>
                        <div class="col-sm-9">
                            <input type="text"  name="col_seo_link"  class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Image</label>
                        <div class="col-sm-9">
                            <button style="width: 70px; display: inline-block; vertical-align: top;" onclick="BrowseServer('col_image_img', 'col_image');" class="btn btn-block btn-primary " >Upload</button>
                            <input  name="col_image_img" type="image" style="max-width: 200px;"  src="" alt="">
                            <input type="hidden" name="col_image"   class="form-control ">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Status</label>
                        <div class="col-sm-9">
                            <div class="checkbox checkbox-switch">
                                <label>
                                    <input name="col_status" value="0" type="checkbox" data-on-color="success" data-off-color="warning" data-on-text="Show" data-off-text="Hide" class="switch" checked="true">
                                    Show/hide
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Decription</label>
                        <div class="col-sm-9">
                            <textarea style="width: 500px; height: 110px;" rows="5" cols="5" class="form-control " id="description_ckeditor" name="col_description" ></textarea>
                        </div>
                    </div>
                </div>


                <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                    <button  type="submit" class="btn btn-primary btn-submit-content">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<p id="demo"></p>
<!-- /horizontal form modal -->
<script type="text/javascript">
    var columns = {'col_id': 'inputtext', 'col_name': 'inputtext', 'col_seo_link': 'inputtext',  'col_image': 'image', 'col_status': 'checkbox-switch', 'col_description': 'ckeditor'};

</script>
