<?php echo $this->partial('my-page/menu') ?>
<div class="container me-body-container">
    <div class="row">
        <div class="col-xs-60">
            <div class="row">
                <div class="col-xs-60">
                    <div class="grid-col-container" id="appeal-alert">
                        <h3 class="page-title">Thông Tin Tài Khoản</h3>
                    </div>
                    <div class="grid-col-container">
                        <div class="me-ui-box">
                            <div id="main-panel" class="main-panel">
                                <!--=====================SCREEN BEGIN==============================================================-->
                                <div class="title-wrap">
                                    <h1 class="guide">Cập nhật thông tin tài khoản</h1>
                                </div>

                                <div id="page960" class="main-box">
                                    <form id="GroupListForm"  class="form-horizontal" onsubmit="return myPage('userInfo','GroupListForm');return false;">
                                        <div align="right"><span class="required">required information</span></div>
                                        <table class="tables V" width="100%" cellspacing="0" cellpadding="0" border="0">
                                            <tbody>
                                            <tr>
                                                <th>
                                                    <span class="required">Mật Khẩu Cũ:</span>
                                                </th>
                                                <td>
                                                    <div class="column subHead">
                                                        <input  required minlength="6" name="current_password"
                                                               type="password">
                                                    </div>
                                                    <div style="clear:both;"></div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <th>
                                                    <span class="required">Mật Khẩu Mới:</span>
                                                </th>
                                                <td>
                                                    <div class="column subHead">
                                                        <input  required minlength="6" name="us_password" type="password">
                                                    </div>
                                                    <div style="clear:both;"></div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <th>
                                                    <span class="required">Lập Lại Mật Khẩu Mới:</span>
                                                </th>
                                                <td>
                                                    <div class="column subHead">
                                                        <input  required minlength="6" name="us_confirm_password"
                                                               type="password">
                                                    </div>
                                                    <div style="clear:both;"></div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td colspan="2" class="button-wrap">
                                                    <button onclick="myPage('userInfo','GroupListForm');" type="button" id="formSubmit" class="dpl-btn">Submit</button>
                                                    <input style="visibility: hidden"  name="Submit" value=" Submit "
                                                           class="dpl-btn" type="submit">
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </form>
                                </div>

                                <div style="clear:both;"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>