<?php //if ($data) { ?>
    <div class="form-group">
        <label class="control-label col-sm-2">Image</label>
        <div class="col-sm-10">

            <form style="min-height: 200px" action="#" class="dropzone" id="dropzone_multiple"></form>
        </div>
    </div>
    <div class="form-group">
        <div class="row grid-image-gallery">

        </div>
    </div>
    <script type="text/javascript">
        var id_image = 0;
        var plo_id = -1;
        var $grid;
        $(document).ready(function () {
            $('[data-popup="lightbox"]').fancybox({
                padding: 3
            });
            $('.select-search-color').select2();
            $(".switch").bootstrapSwitch();


            $grid = $('.grid-image-gallery').masonry({
                itemSelector: '.gallery-image',
                // use element for option
                // columnWidth: 240,
                percentPosition: true,
//                gutter: 10
            });
            $grid.imagesLoaded().progress(function () {
                $grid.masonry('layout');
            });
            getImageDatabase(-1);
        });
        function getImageDatabase(id) {
            plo_id = id;
            $.ajax({
                type: "POST",
                url: queryUrl + "/detail-content",
                data: {"color_id": id},
                success: function (result) {
                    $(".gallery-image").remove();
                    var data = $.parseJSON(result);
                    if (data.product_status == 1) {
                        $('input[name="product_status"]').bootstrapSwitch('state', true);
                    } else {
                        $('input[name="product_status"]').bootstrapSwitch('state', false);
                    }
                    //                            $(".gallery-image").remove();
                    if (data.image.length != 0) {
                        $.each(data.image, function (key, val) {
                            var html = '';
                            html = '<div class="col-lg-3 col-sm-6 gallery-image gallery-image-' + val.ga_id + '">\n\
                                    <div class="thumbnail">\n\
                                        <div class="thumb">\n\
                                            <img src="' + rootUrl + val.ga_image_link + '" alt="">\n\
                                            <input type="hidden" name="ga_image_link" value="' + val.ga_image_link + '">\n\
                                            <div class="caption-overflow">\n\
                                                <span>\n\
                                                    <a href="' + rootUrl + val.ga_image_link + '" data-popup="lightbox" rel="gallery" class="btn border-white text-white btn-flat btn-icon btn-rounded"><i class="icon-zoomin3"></i></a>\n\
                                                    <a onclick="deleteImage(' + val.ga_id + ')" href="javascript:;" class="btn border-danger text-danger-600 btn-flat btn-icon btn-rounded btn-remove-attribute"><i class="icon-minus3"></i></a>\n\
                                                </span>\n\
                                            </div>\n\
                                        </div>\n\
                                    </div>\n\
                                </div>';
                            var $content = $(html);
                            $grid.append($content).masonry('appended', $content);
                            $grid.imagesLoaded().progress(function () {
                                $grid.masonry('layout');
                            });
//                            $(".grid-image-gallery").append(html);
                            id_image = val.ga_id;
                        });
                        $("[data-popup='lightbox']").fancybox({
                            padding: 3
                        });
                    }
                    uploadImage();
                }
            });
        }
        function uploadImage() {
            var pr_id = 1;
//            var plo_id = $("#select-search-color").val();
            var myDropzone = new Dropzone("#dropzone_multiple", {
                init: function () {
                    this.on("addedfile", function (file) {
                        // Create the remove button
                        var removeButton = Dropzone.createElement("<a onclick='deleteImage(" + id_image + ")' href='javascript:;' class='dz-remove' >Remove file</a>");


                        // Capture the Dropzone instance as closure.
                        var _this = this;

                        // Listen to the click event
                        removeButton.addEventListener("click", function (e) {
                            // Make sure the button click doesn't submit the form:
                            e.preventDefault();
                            e.stopPropagation();

                            // Remove the file preview.
                            _this.removeFile(file);
                            // If you want to the delete the file on the server as well,
                            // you can do the AJAX request here.
                        });

                        // Add the button to the file preview element.
                        file.previewElement.appendChild(removeButton);
                    });
                },
                url: queryUrl + "/upload-image",
                filesizeBase: 1024,
                //                uploadMultiple: true,
                //                addRemoveLinks: true,
                dictRemoveFile: "Remove zxc",
                paramName: pr_id, // The name that will be used to transfer the file
                dictDefaultMessage: 'Drop files to upload <span>or CLICK</span>',
                maxFilesize: 2, // MB
                maxFiles: 20,
                acceptedFiles: "image/jpeg,image/png",
                accept: function (file, done) {
                    var html = '';
                    html = '<div style="height: 0px;visibility: hidden" class="col-lg-3 col-sm-6 gallery-image gallery-image-' + id_image + '">\n\
                                    <div class="thumbnail">\n\
                                        <div class="thumb">\n\
                                            <img src="' + rootUrl + 'public/uploads/images/upload/' + file.name + '" alt="">\n\
                                            <input type="hidden" name="pi_image_link" value="public/uploads/images/upload/' + file.name + '">\n\
                    <div class="caption-overflow">\n\
                    <span>\n\
                <a href="' + rootUrl + 'public/uploads/images/upload/' + file.name + '" data-popup="lightbox" rel="gallery" class="btn border-white text-white btn-flat btn-icon btn-rounded"><i class="icon-zoomin3"></i></a>\n\
            <a onclick="deleteImage(' + id_image + ')" href="javascript:;" class="btn border-danger text-danger-600 btn-flat btn-icon btn-rounded btn-remove-attribute"><i class="icon-minus3"></i></a>\n\
        </span>\n\
            </div>\n\
        </div>\n\
                                    </div>\n\
                                </div>';
                    $(".grid-image-gallery").append(html);
                    $('[data-popup="lightbox"]').fancybox({
                        padding: 3
                    });
                    id_image++;
                    done();
                },
            });
            myDropzone.on("success", function (file, responseText) {
                var result = $.parseJSON(responseText);
                if (result.status == 0) {
                    WarningNotice('Lỗi', result.message);
                    myDropzone.removeFile(file);
                    $(".gallery-image").remove();
                }


            });
            myDropzone.on("queuecomplete", function (file, responseText) {
                alert("Upload success");
                window.location.reload();

            });
        }
        function deleteImage(id) {
            $.ajax({
                type: "POST",
                url: queryUrl + '/handle',
                data: {method: "deleteContent", id: id},
                success: function (response) {

                    var data = $.parseJSON(response);
                    if (data.status == 1) {
                        $(".gallery-image-" + id).remove();
                    }
                },
                error: function (xhr, ajaxOptions, thrownError) {
                }
            });

        }
    </script>
<?php //} ?>