<div id="content">
    <div class="content-layout">
        <div class="maincenter">
            <div class="maincenter-box">
                <div class="maincenter-box-tip">
                    <p class="ui-tiptext ui-tiptext-message ft-14">
                        <i class="ui-tiptext-icon iconfont" title="Note"></i>
                        Vui lòng nhập email để lấy lại mật khẩu.
                    </p>
                </div>
                <form class="ui-form form-horizontal" id="forgot-form" onsubmit="forgotPasswordUser(); return false; " >
                    <div class="ui-form-item">
                        <label class="ui-label">Email:</label>
                        <input required email="true" name="us_email" class="ui-input" placeholder="Email"  type="text">

                    </div>

                    <div class="ui-form-item ui-form-item-last">
                        <input value="Submit" class="ui-button ui-button-lorange" id="submitBtn" onclick="forgotPasswordUser();"  type="button">
                    </div>
                </form>


            </div>
        </div>
    </div>
</div>