<!-- Main content -->
<div class="content-wrapper">

    <!-- Page header -->
    <div class="page-header">
        <div class="page-header-content">
            <div class="page-title">
                <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold"><?php echo $header_title; ?></span></h4>
            </div>
        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb">
                <li><a href="<?php echo $urlModule; ?>"><i class="icon-home2 position-left"></i> Home</a></li>
                <li class="active"><?php echo $header_title; ?></li>
            </ul>

        </div>
    </div>
    <!-- /page header -->


    <!-- Content area -->
    <div class="content">




        <!-- Custom button -->
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title"><?php echo $header_title; ?></h5>
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="reload"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>
            <div class="panel-body">
                <form onsubmit="return false" class="form-horizontal ">
                    <div class="modal-body">
                        <div class="form-group">
                            <label class="control-label col-sm-2">Product </label>
                            <div class="col-sm-10">
                                <select id="select-product"  name="pr_id" class="select-search">
                                    <option value="-1">Chose</option>
                                    <?php
                                    if ($product) {
                                        foreach ($product as $val) {
                                            ?>
                                            <option  value="<?php echo $val->pr_id ?>"><?php echo $val->pr_name ?></option>
                                            <?php
                                        }
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="content-gallery">
                            
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button  type="submit" class="btn btn-primary btn-submit-content">Save</button>
                    </div>
                </form>
            </div>


        </div>
        <!-- /custom button -->
    </div>
    <!-- /content area -->

</div>
<!-- /main content -->
<script type="text/javascript">
    $(document).ready(function () {
        $("#select-product").change(function () {
            var id = $(this).val();
            $.get(queryUrl + "/detail-content?id=" + id, function (data) {
                $(".content-gallery").html(data);
            });


        });
    });
</script>