<!-- Main content -->
<div class="content-wrapper">

    <!-- Page header -->
    <div class="page-header">
        <div class="page-header-content">
            <div class="page-title">
                <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold"><?php echo $header_title; ?></span></h4>
            </div>
        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb">
                <li><a href="<?php echo $urlModule; ?>"><i class="icon-home2 position-left"></i> Home</a></li>
                <li class="active"><?php echo $header_title; ?></li>
            </ul>

        </div>
    </div>
    <!-- /page header -->


    <!-- Content area -->
    <div class="content">




        <!-- Custom button -->
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title"><?php echo $header_title; ?></h5>
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="reload"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>
            <a target="_blank" href="<?php echo $this->url->get("backend/product/detail-content") ?>" style="margin-left: 20px;" class="btn btn-success btn-labeled"><b><i class="icon-plus3"></i></b> New Data</a>
            <table class="table table-bordered table-hover datatable-highlight">
                <thead>
                    <tr class="success">
                        <th>ID</th>
                        <th>Manufacture</th>
                        <th>Category</th>
                        <th>ID Product</th>
                        <th>Image</th>
                        <th>Name</th>
                        <th>Price Promotion</th>
                        <th>Quantity</th>
                        <th>Product Status</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($data) { ?>
                        <?php foreach ($data as $key => $val) { ?>
                            <tr >
                                <td><?php echo $val->pr_id ?></td>
                                <td><?php echo $val->CategoryModel->ManufacturerModel->ma_name ?></td>
                                <td><?php echo $val->CategoryModel->ct_name ?></td>
                                <td><?php echo $val->pr_public_id ?></td>
                                <td><img style="max-width: 100px;" src="<?php echo $val->showImage();?>" alt=""> </td>
                                <td><?php echo $val->pr_name ?></td>
                                <td style="color:red" >
                                    <?php
                                        if ($val->pr_price_promotion != 0) {
                                            echo number_format($val->pr_price_promotion) . " VNĐ";
                                        }
                                        ?>
                                </td>
                                <td><?php echo $val->pr_quantity ?></td>
                                <td>
                                    <?php if ($val->product_status == 1) { ?>
                                        <span class="label label-success">Còn Hàng</span>
                                    <?php } else { ?>
                                        <span class="label label-danger">Hết Hàng</span>
                                    <?php } ?>
                                </td>
                                <td>
                                    <?php if ($val->pr_status == 1) { ?>
                                        <span class="label label-success">Show</span>
                                    <?php } else { ?>
                                        <span class="label label-warning">Hide</span>
                                    <?php } ?>
                                </td>
                                <td>
                                    <a href="<?php echo $this->url->get("backend/product/detail-content?id=") . $val->pr_id ?>" target="_blank" class="btn btn-info btn-icon btn-edit-content"><i class="icon-pencil7"></i></a>
                                    <button data-rel="<?php echo $val->pr_id ?>" data-original-title="Remove" data-popup="tooltip" type="button" class="btn btn-danger btn-icon btn-delete-content">
                                        <i class="icon-trash"></i>
                                    </button>
                                </td>
                            </tr>
                            <?php
                        }
                    }
                    ?>
                </tbody>
            </table>
        </div>
        <!-- /custom button -->
    </div>
    <!-- /content area -->

</div>
<!-- /main content -->
