<style>
    .error{
        color: red;
    }
</style>
<!-- Horizontal form modal -->
<div id="modal_form_horizontal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h5 class="modal-title"><?php echo $header_title; ?></h5>
            </div>

            <form enctype="multipart/form-data" method="post" onsubmit="return false;" class="form-horizontal ">
                <div class="modal-body">
                    <input type="hidden" name="ag_id"  class="form-control">
                    <div class="form-group">
                        <label class="control-label col-sm-3">Name</label>
                        <div class="col-sm-9">
                            <input type="text"  required="true" name="ag_name"  class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Address</label>
                        <div class="col-sm-9">
                            <input type="text"  required="true" name="ag_address"  class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Tỉnh/Thành Phố</label>
                        <div class="col-sm-9">
                            <select onchange="changeProvince()" id="province"  name="zp_id" class="select-search ">
                                <option value="-1">Chose</option>
                                <?php
                                if (isset($province)) {
                                    foreach ($province as $val) {
                                        ?>
                                        <option  value="<?php echo $val->zp_id ?>"><?php echo $val->zp_name ?></option>
                                        <?php
                                    }
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                </div>


                <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                    <button  type="submit" class="btn btn-primary btn-submit-content">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<p id="demo"></p>
<!-- /horizontal form modal -->
<script type="text/javascript">
    var columns = {'ag_id': 'inputtext', 'ag_name': 'inputtext', 'ag_address': 'inputtext','zp_id': 'zone'};
</script>

