<!-- Main content -->
<div class="content-wrapper">

    <!-- Page header -->
    <div class="page-header">
        <div class="page-header-content">
            <div class="page-title">
                <h4><i class="icon-arrow-left52 position-left"></i> <span
                        class="text-semibold"><?php echo $header_title; ?></span></h4>
            </div>
        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb">
                <li><a href="<?php echo $urlModule; ?>"><i class="icon-home2 position-left"></i> Home</a></li>
                <li class="active"><?php echo $header_title; ?></li>
            </ul>

        </div>
    </div>
    <!-- /page header -->


    <!-- Content area -->
    <div class="content">


        <!-- Custom button -->
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title"><?php echo $header_title; ?></h5>
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="reload"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>
            <div style="width: 95%;margin: 0 auto;background-color: rgb(249, 249, 249)">

                <!-- Basic layout-->
                <form class="search-form" onsubmit="return false;" method="post">
                    <div style="background: none" class="panel panel-flat">
                        <div style="background: none" class="panel-heading">
                            <h5 class="panel-title">Filter</h5>

                        </div>
                        <div class="panel-body">
                            <div class="row" style="margin-bottom: 15px;">
                                <div class="col-md-4">
                                    <label>Order ID:</label>
                                    <input type="text" name="or_public_id" class="form-control" placeholder="Order ID">
                                </div>
                                <div class="col-md-4">
                                    <label>Order Status:</label>
                                    <select name="os_id" class="select-search">
                                        <option value="-1">Chose</option>
                                        <?php foreach ($order_status as $val) { ?>
                                            <option
                                                value="<?php echo $val->os_id ?>"><?php echo $val->os_name ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                                <div class="col-md-4">
                                    <label>From Date:</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="icon-calendar22"></i></span>
                                        <input name="from_date" class="form-control daterange-single"
                                               value="<?php echo date("Y-m-d", strtotime('-1 month', time())); ?>"
                                               type="text">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <label>Email Customer:</label>
                                    <input type="text" email="true" name="or_email" class="form-control"
                                           placeholder="Email Customer">
                                </div>
                                <div class="col-md-4">
                                    <label>Total:</label>
                                    <input number="true" type="text" name="or_total" class="form-control"
                                           placeholder="Total">
                                </div>
                                <div class="col-md-4">
                                    <label>To Date:</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="icon-calendar22"></i></span>
                                        <input name="to_date" class="form-control daterange-single"
                                               type="text">
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer" style="top: 17px; position: relative;">
                                <button onclick="searchFilter('order');" type="submit" class="btn btn-primary">Search<i
                                        class="icon-search4 position-right"></i></button>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- /basic layout -->

            </div>
            <div class="filter-search">
                <table class="table table-bordered table-hover datatable-highlight">
                    <thead>
                    <tr class="success">
                        <th>ID</th>
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Email Customer</th>
                        <th>Total</th>
                        <th>Payment Type</th>
                        <th>Date Added</th>
                        <th>Order Status</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if ($data) { ?>
                        <?php foreach ($data as $key => $val) { ?>
                            <tr>
                                <td><?php echo $val->or_id ?></td>
                                <td><?php echo $val->or_public_id ?></td>
                                <td><?php echo $val->or_name ?></td>
                                <td><?php echo $val->or_email ?></td>
                                <td><?php echo number_format($val->or_total) . " VNĐ" ?></td>
                                <td><?php echo $val->or_payment_type ?></td>
                                <td><?php echo $val->or_create_date ?></td>
                                <td><?php echo $val->OrderStatusModel->os_name ?></td>
                                <td>
                                    <a href="<?php echo $this->url->get("backend/order/order-detail?id=") . $val->or_id ?>"
                                       class="btn btn-success btn-icon"><i class="icon-eye"></i></a>

                                    <button onclick="showPopup(<?php echo $val->or_id ?>)" data-original-title="Edit"
                                            data-toggle="modal" data-target="#modal_form_horizontal"
                                            data-popup="tooltip"
                                            type="button" class="btn btn-info btn-icon btn-edit-content">
                                        <i class="icon-pencil7"></i>
                                    </button>


                                </td>
                            </tr>
                            <?php
                        }
                    }
                    ?>

                    </tbody>
                </table>
            </div>
            <?php echo $this->partial($this->dispatcher->getControllerName() . '/neweditcontent') ?>
        </div>
        <!-- /custom button -->
    </div>
    <!-- /content area -->

</div>
<!-- /main content -->
