<div id="print-body">
    <table style="width: 100%;">
        <tbody>
        <tr>
            <td style="width: 5%;">
                <br>
            </td>
            <td style="width: 20%;"><img
                    src="<?php echo $this->config['rootUrl'] . "public/BackendMD/" ?>assets/images/logo_demo.png"
                    class="content-group mt-10" alt="" style="width: 120px;"></td>
            <td style="width: 20%;">
                <br>
            </td>
            <td style="width: 20%; text-align: right;">

                <h5 class="text-uppercase text-semibold">Invoice# <?php echo $data->or_public_id ?></h5>

            </td>
            <td style="width: 5%;">
                <br>
            </td>
        </tr>
        <tr>
            <td style="width: 5%;">
                <br>
            </td>
            <td style="width: 20%;">

                <ul class="list-condensed list-unstyled">
                    <li>Địa chỉ cửa h&agrave;ng</li>
                </ul>
            </td>
            <td style="width: 20%;">
                <br>
            </td>
            <td style="width: 20%; text-align: right;">

                <ul class="list-condensed list-unstyled">
                    <li>Ngày: <span
                            class="text-semibold"><?php echo date("d/m/Y", strtotime($data->or_create_date)) ?></span>
                    </li>
                </ul>
            </td>
            <td style="width: 5%;">
                <br>
            </td>
        </tr>
        <tr>
            <td style="width: 5%;">
                <br>
            </td>
            <td style="width: 20%;"><span class="text-muted">Địa Chỉ Giao H&agrave;ng:</span></td>
            <td style="width: 20%;">
                <br>
            </td>
            <td style="width: 20%; text-align: right;"><span class="text-muted">Th&ocirc;ng Tin Kh&aacute;ch H&agrave;ng:</span>
            </td>
            <td style="width: 5%;">
                <br>
            </td>
        </tr>
        <tr>
            <td style="width: 5%;">
                <br>
            </td>
            <td style="width: 20%;">

                <ul class="list-condensed list-unstyled">
                    <li><h5><?php echo $data->or_name ?></h5></li>
                    <li><span class="text-semibold">Địa chỉ: <?php echo $data->or_address ?></span></li>
                    <li><?php echo $data->ZoneDistrictModel->zd_name ?></li>
                    <li><?php echo $data->ZoneProvinceModel->zp_name ?></li>
                    <li>SĐT : <?php echo $data->or_phone ?></li>
                    <li><a href="javascript:;"><?php echo $data->or_email ?></a></li>
                </ul>
            </td>
            <td style="width: 20%;">
                <br>
            </td>
            <td style="width: 20%; text-align: right;">

                <ul class="list-condensed list-unstyled invoice-payment-details">
                    <li><h5>ID: <?php echo $data->UserModel->us_id ?></h5></li>
                    <li><h5><?php echo $data->UserModel->us_full_name ?></h5></li>
                    <li><?php echo $data->UserModel->us_phone ?></li>
                    <li><a href="javascript:;"><?php echo $data->UserModel->us_email ?></a></li>
                </ul>
            </td>
            <td style="width: 5%;">
                <br>
            </td>
        </tr>
        </tbody>
    </table>


    <div class="table-responsive">
        <table class="table table-lg">
            <thead>
            <tr>
                <th class="col-sm-1">STT</th>
                <th>Sản Phẩm</th>
                <th>Màu</th>
                <th>Size</th>
                <th class="col-sm-1">Số Lượng</th>
                <th class="col-sm-2">Đơn Giá</th>
                <th class="col-sm-2">Total</th>
            </tr>
            </thead>
            <tbody>
            <?php
            $i = 1;
            foreach ($data->OrderDetailModel as $detail) {
                ?>
                <tr>
                    <td><?php echo $i++; ?></td>
                    <td>
                        <h6 class="no-margin"><?php echo $detail->ProductModel->pr_name ?></h6>
                    </td>
                    <td><?php echo isset($detail->ColorModel) ? $detail->ColorModel->plo_name : '' ?></td>
                    <td><?php echo isset($detail->SizeModel) ? $detail->SizeModel->plo_name : '' ?></td>
                    <td><?php echo $detail->od_quantity ?></td>
                    <td><?php echo number_format($detail->od_price) . " VNĐ" ?></td>
                    <td><span
                            class="text-semibold"><?php echo number_format($detail->od_total_price) . " VNĐ" ?></span>
                    </td>
                </tr>
            <?php } ?>

            </tbody>
        </table>
    </div>

    <div class="panel-body">
        <div class="row invoice-payment">
            <div class="col-sm-7">

            </div>

            <div class="col-sm-5">
                <div class="content-group">
                    <h6>Total due</h6>
                    <div class="table-responsive no-border">
                        <table class="table">
                            <tbody>
                            <tr>
                                <th>Thành Tiền:</th>
                                <td class="text-right"><?php echo $data->setPrice($data->or_total - $data->or_discount - $data->or_fee_drive); ?></td>
                            </tr>
                            <tr>
                                <th>Discount:</th>
                                <td class="text-right"><?php echo $data->setPrice($data->or_discount); ?></td>
                            </tr>
                            <tr>
                                <th>Phí Giao Hàng:</th>
                                <td class="text-right"><?php echo $data->setPrice($data->or_fee_drive); ?></td>
                            </tr>
                            <tr>
                                <th>Tổng Tiền:</th>
                                <td class="text-right text-primary"><h5
                                        class="text-semibold"><?php echo $data->showPrice() ?></h5></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>