<style>
    .error{
        color: red;
    }
</style>
<!-- Horizontal form modal -->
<div id="modal_form_horizontal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h5 class="modal-title"><?php echo $header_title; ?></h5>
            </div>

            <form enctype="multipart/form-data" method="post" onsubmit="return false;" class="form-horizontal ">
                <div class="modal-body">
                    <input type="hidden" name="ma_id"  class="form-control">
                    <div class="form-group">
                        <label class="control-label col-sm-3">Name</label>
                        <div class="col-sm-9">
                            <input type="text"  required="true" name="ma_name"  class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Decription</label>
                        <div class="col-sm-9">
                            <textarea style="width: 500px; height: 110px;" rows="5" cols="5" class="form-control" name="ma_description" ></textarea>
                        </div>
                    </div>

                </div>


                <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                    <button  type="submit" class="btn btn-primary btn-submit-content">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<p id="demo"></p>
<!-- /horizontal form modal -->
<script type="text/javascript">
    var columns = {'ma_id':'inputtext','ma_name': 'inputtext', 'ma_description': 'textarea'};
</script>

